title: "Learned Systems"
author: "MIT DSG"
description: "A blog about research on learned systems."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # hide the box-shadow from header and footer

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "about.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Accessibility, url: "http://accessibility.mit.edu/"}
  - {title: Subscribe, url: "https://forms.gle/YVYXRi729aJPA3tg8"}
  - {title: Mail, icon: envelope, url: "mailto:learnedsystems@mit.edu"}
  - {title: GitHub, icon: github, url: "https://github.com/learnedsystems"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
